### ISSUE TITLE
No connection since update to 0.2.8

### ISSUE THREAD

**Issue by Smarthome-Creator** [aegjoyce/custom-ambilight#4]
Hello,
unfortunately, since the update and the new connection option, your integration can no longer connect to the TV.

It definitely worked up to version 0.2.5 and the connection method via user name and password.
Now that I only have to specify the host, a connection is simply no longer established.
Unfortunately, it no longer works with the latest version either.

Do you have any idea what the problem could be? Nothing has changed in my setup, only HA is up to date.

<img width="995" alt="Bildschirmfoto 2024-11-24 um 20 16 11" src="https://github.com/user-attachments/assets/f73569dc-c743-4a3e-8649-ee18bfa56307">

**Comment by aegjoyce** [comment]
Have you tried removing the integration and setting it up again?

If this doesn't work then revert to 0.2.5 for now and I will add an option during onboarding to choose between HTTP and HTTPS connection so you can make it work with your TV

**Comment by Smarthome-Creator** [comment]
I have also tried a reinstallation, unfortunately the same problem.
I will try the 0.2.5 version again. Can you perhaps give me a link to your old documentation on how to retrieve the access data from the TV? I no longer have that in my head.

I can also wait for the next version of your integration, it's ok for me.

**Comment by aegjoyce** [comment]
I have released v0.2.10 with a new onboarding that lets you choose between http and https setup - tested successfully on both connections on my tv, would you mind trying on yours?

**Comment by Smarthome-Creator** [comment]
@aegjoyce , works again, thank you.
